### ISSUE TITLE
b4a update replaces b4a executable with GitHub 404 Page

### ISSUE THREAD

**Issue by appliquette** [back4app/parse-cli#11]
To replicate:
```
curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash
b4a update
b4a
```

Output:
```
/usr/local/bin/b4a: line 1: syntax error near unexpected token `newline'
/usr/local/bin/b4a: line 1: `<!DOCTYPE html>'
```

**Comment by iurisilvio** [comment]
Thanks for your report. It was fixed today and released. Of course you have to update manually, because all versions since the fork have the same issue.

**Comment by iurisilvio** [comment]
I added some fallback files to serve old clients. You're now able to run the command to update the binary.
