### ISSUE TITLE
Downloading b4a.exe from release_3.1 triggers malware warning

### ISSUE THREAD

**Issue by bodagetta** [back4app/parse-cli#13]
Windows Defender Advanced Threat Protection identified b4a.exe from release_3.1 as malware.

The specific message is

Windows Defender AV detected 'Fuerboos' malware

**Comment by iurisilvio** [comment]
It is a false positive.

Google searching for `Fuerboos malware`, I found several github issues reporting the same issue.

Based on hashicorp/terraform#16539, Hashicorp even asked Windows Defender team and they confirmed the false positive. It is not exact science.

https://github.com/crazy-max/WindowsSpyBlocker/wiki/miscFAQ#antivirus-complains-about-windowsspyblocker
https://www.google.com.br/search?q=Fuerboos+malware&source=lnt&tbs=qdr:m&sa=X&ved=0ahUKEwjYyOr8ytnXAhWTl5AKHfDIAYoQpwUIHw&biw=1366&bih=629

It is probably related to golang, this is our first release with 1.9 (to fix a OSX issue). The other issues I found are golang projects too.

That said, I think it is important to fix the issue to support Windows users.
