### ISSUE TITLE
Feature Request: show help when just running "b4a"

### ISSUE THREAD

**Issue by ivnnv** [back4app/parse-cli#19]
I almost always forget to write "b4a list" or "b4a -h" 🤦‍♂  and when you just launch "b4a" without any parameters, it shown an error:

```
parse: api error with message="unsupported method: "
/home/travis/gopath/src/github.com/back4app/parse-cli/main.go:123           checkIfSupported
/home/travis/gopath/src/github.com/back4app/parse-cli/main.go:81            main
/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/proc.go:185      main
```
So I think it would be cool to replace this error for something more usable like the help page or just a message telling you to add a parameter.

Cheers!

**Comment by charles-ramos** [comment]
Thanks! `b4a` command currently returns the same results of `b4a -h`
