### ISSUE TITLE
error when adding new or existing project using "b4a new"

### ISSUE THREAD

**Issue by kp96-info** [back4app/parse-cli#20]
i am following this document https://www.back4app.com/docs/platform/parse-cli

and at this step -> [step](https://www.back4app.com/docs/platform/parse-cli#step-3---create-a-new-back4app-app)

i am getting this below error ->
 parse: error with status=500 and body="Internal Server Error\n"
```
Would you like to create a new app, or add Cloud Code to an existing app?
Type "(n)ew" or "(e)xisting": e
parse: error with status=500 and body="Internal Server Error\n"
```

**Comment by charles-ramos** [comment]
@kp96-info What's the Operational System of your machine?
