### ISSUE TITLE
Darwin configure error

### ISSUE THREAD

**Issue by EPage-Ed** [back4app/parse-cli#21]
Running the configure command with any option other than accountkey fails:

parse: api error with message="unsupported method: configure email"
/home/travis/gopath/src/github.com/back4app/parse-cli/main.go:123           checkIfSupported
/home/travis/gopath/src/github.com/back4app/parse-cli/main.go:81            main
/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/proc.go:185      main
/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/asm_amd64.s:2337 goexit

This is on a Mac running Mac OS 10.15.4.

**Comment by charles-ramos** [comment]
Is your machine running on Apple Silicon M1? We updated the installer recently and it should work properly now, please let me know if the issue still persists.

**Comment by kamilpowalowski** [comment]
Apple M1 was introduced in November 2020 and OP comment is from Jul 2020. 
But I have an M1 iMac and I had a similar issue:
```
parse: api error with message="unsupported method: "
/Users/charlesramos/go/src/github.com/back4app/main.go:123 checkIfSupported
/Users/charlesramos/go/src/github.com/back4app/main.go:81  main
/usr/local/go/src/runtime/proc.go:225                      main
/usr/local/go/src/runtime/asm_arm64.s:1130                 goexit
```

**Comment by charles-ramos** [comment]
Hi @kamilpowalowski, could you please delete the `.back4app` folder available at `/Users/<your_user>/` and try to install it once again?

Also, please, uninstall the CLI tool, for that, just delete the `b4a` file available at `/usr/local/bin`.

Please, let me know your results.

**Comment by charles-ramos** [comment]
The installer was updated to recognize M1 processors https://github.com/back4app/parse-cli/pull/27

Install it again, you might be able to make it work. This guide will help you with that: https://www.back4app.com/docs/platform/parse-cli
