### ISSUE TITLE
b4a doesn't run

### ISSUE THREAD

**Issue by j4hangir** [back4app/parse-cli#22]
I have tried auto-installing and manual installing on Kali Linux (subsystem on W10), I only get:
`zsh: exec format error: b4a`

Interesting enough, I could compile with Go and get `parse-cli`, but I guess b4a wraps around that one?

**Comment by charles-ramos** [comment]
Hi @j4hangir, we recently released an update, could you please check if this issue still persists?

If so, could you please run the command ```uname -pm``` in your machine and send me the results?

We also provide a docker image that might be used for that, have you already tried it?

Here's the link: https://hub.docker.com/r/back4app/b4a_cli

**Comment by j4hangir** [comment]
Sorry I cannot test it anymore, not even on Windows for the time being..!

**Comment by charles-ramos** [comment]
Hi @j4hangir, thanks for your feedback, in case you face any problems with the project, feel free to create a new issue.

For general support, you can contact our team here: https://www.back4app.com/support
