### ISSUE TITLE
b4a error:`Segmentation fault: 11` when run on macOS 11.2.2 Apple Silcon

### ISSUE THREAD

**Issue by dbj** [back4app/parse-cli#23]
I installed the b4a utility by running `curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash` on my macOS 11.2.2 Apple Silicon Mini. The installation appeared to go OK.

When I run the utility, I get the following error: `Segmentation fault: 11`

**Comment by ghost** [comment]
The same error on Apple MacBook Air (M1 Apple Silicon), macOS 11.2.3

**Comment by mistralaix** [comment]
Same error. Anyone figured a way to fix it or a trick to pass by it?

**Comment by charles-ramos** [comment]
It's fixed https://github.com/back4app/parse-cli/pull/27
