### ISSUE TITLE
error on install b4a cli on docker image

### ISSUE THREAD

**Issue by omurilo** [back4app/parse-cli#29]
On docker image of node:alpine the installation of b4a cli is failed on select of system architecture.

`uname -p` return `unknown`.

On the #28 I'll add the solution to the problem.

**Comment by charles-ramos** [comment]
@omurilo Can you please check this one https://github.com/back4app/parse-cli/pull/31 ?

**Comment by omurilo** [comment]
@charles-ramos I needn't test, you changed to  `uname -pm`, so that is functional.

**Comment by charles-ramos** [comment]
@omurilo the PR https://github.com/back4app/parse-cli/pull/31 is merged, can you please check if the issue still persists?
