### ISSUE TITLE
`installer.sh` script doesn't work on Bitbucket pipelines (running under Docker image `image: node:16.3.0`)

### ISSUE THREAD

**Issue by smuravev** [back4app/parse-cli#30]
Please see more details about this issue, here: https://github.com/back4app/parse-cli/commit/6c093adb09dbd54362d47942058533e8fd29a481#commitcomment-53540017

Here is screenshot:

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/738748/125822542-434c6927-5718-46ba-9841-df26c1e411a8.png">

FYI: `uname -p` returns `unknown` value on Bitbucket pipeline (Docker image) - see screenshot below:

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/738748/125824367-4fc8c32a-3ed3-4dc0-846b-29b9bf0c7234.png">

**Comment by charles-ramos** [comment]
Hi @smuravev, I just tested it here, and it worked properly, as you can see below:

<img width="802" alt="Captura de Tela 2021-07-15 às 22 11 40" src="https://user-images.githubusercontent.com/25464287/125876939-751ac35a-7fa8-4b63-9d6b-c90e2456017f.png">

Am I missing anything?

**Comment by smuravev** [comment]
Hi @charles-ramos ,

Thnx for you reply. Can you please share your `bitbucket-pipelines.yml` file.

We use the `image: node:16.3.0` Docker image in our `bitbucket-pipelines.yml` file.

Here is an example - can you please use it in your test ?

```
# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:16.3.0

pipelines:
# NOTE [smuravev] We temporary disabled DEFAULT pipelines - fires if we push changes to origin/task aware branches.
#                 It's disabled because unused now and because it produces Slack spamming in #pipelines channel.
#                 To make it enabled further, just uncomment the following lines.
#  default:
#    - step:
#        script:
#          - npm install

  branches:
    master:
      - step:
          script:
            - uname -p
            - curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | /bin/bash
            - b4a version
```

**Comment by charles-ramos** [comment]
@smuravev thanks for sharing it!

There's a pull request to fix it https://github.com/back4app/parse-cli/pull/31 and it will be merged soon.

I tested the `uname -pm` command and it will work properly after its merge.

**Comment by charles-ramos** [comment]
@smuravev the PR https://github.com/back4app/parse-cli/pull/31 is merged, can you please check if the issue still persists?

**Comment by smuravev** [comment]
Hi @charles-ramos ,

I have just tested your fix on our Bitbucket pipeline and on my Mac M1 (chip) - it seems everything works well.
Thank you very much for your fix.

**Comment by charles-ramos** [comment]
Great! Thanks for letting me know! :)
https://github.com/back4app/parse-cli/pull/31
