### ISSUE TITLE
fatal error: runtime: bsdthread_register error

### ISSUE THREAD

**Issue by ApoAdrian** [back4app/parse-cli#32]
I have just update to macOS Monterrey 12.0.1 my MacbookPro (i5 2018) and now I'm getting this error every time I try to call `b4a` command

I have update it with
`curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash`:
```
Version 3.3.1 will be installed
######################################################################## 100,0%#=#=-#  #                                                                     
Installing ...
Installation finished
```

but when I call `b4a`:
```
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x145211f, 0x21)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/panic.go:605 +0x95 fp=0x7ff7bfeff420 sp=0x7ff7bfeff400 pc=0x1029ab5
runtime.goenvs()
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/os_darwin.go:108 +0x83 fp=0x7ff7bfeff450 sp=0x7ff7bfeff420 pc=0x1027353
runtime.schedinit()
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/proc.go:482 +0xa1 fp=0x7ff7bfeff490 sp=0x7ff7bfeff450 pc=0x102c461
runtime.rt0_go(0x7ff7bfeff4c8, 0x1, 0x7ff7bfeff4c8, 0x0, 0x1000000, 0x1, 0x7ff7bfeff6a0, 0x0, 0x7ff7bfeff6a4, 0x7ff7bfeff6b4, ...)
        /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7ff7bfeff498 sp=0x7ff7bfeff490 pc=0x10547bb
```

I have also update go version:
`go version`:
`go version go1.17.2 darwin/amd64`

**Comment by 0biWanKenobi** [comment]
Same exact issue. b4a cli is unusable on Monterey. How about giving this issue _some_ consideration after twenty days of radio silence? Thanks.

**Comment by boardmain** [comment]
Any news?

**Comment by boardmain** [comment]
i reinstalled it but using the bash ( you you use zsh or other shell, before call the curl install)

**Comment by boardmain** [comment]
> I have just update to macOS Monterrey 12.0.1 my MacbookPro (i5 2018) and now I'm getting this error every time I try to call `b4a` command
> 
> I have update it with `curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash`:
> 
> ```
> Version 3.3.1 will be installed
> ######################################################################## 100,0%#=#=-#  #                                                                     
> Installing ...
> Installation finished
> ```
> 
> but when I call `b4a`:
> 
> ```
> fatal error: runtime: bsdthread_register error
> 
> runtime stack:
> runtime.throw(0x145211f, 0x21)
>         /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/panic.go:605 +0x95 fp=0x7ff7bfeff420 sp=0x7ff7bfeff400 pc=0x1029ab5
> runtime.goenvs()
>         /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/os_darwin.go:108 +0x83 fp=0x7ff7bfeff450 sp=0x7ff7bfeff420 pc=0x1027353
> runtime.schedinit()
>         /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/proc.go:482 +0xa1 fp=0x7ff7bfeff490 sp=0x7ff7bfeff450 pc=0x102c461
> runtime.rt0_go(0x7ff7bfeff4c8, 0x1, 0x7ff7bfeff4c8, 0x0, 0x1000000, 0x1, 0x7ff7bfeff6a0, 0x0, 0x7ff7bfeff6a4, 0x7ff7bfeff6b4, ...)
>         /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7ff7bfeff498 sp=0x7ff7bfeff490 pc=0x10547bb
> ```
> 
> I have also update go version: `go version`: `go version go1.17.2 darwin/amd64`

install the cli using the bash shell and not the zsh or the one are you using

**Comment by sebastian-curland** [comment]
Hi, are you planning to fix this? b4a cli does not work in  macOS Monterrey.
Here's a description of the error in Go's repository: https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue

**Comment by charles-ramos** [comment]
Hi @sebastian-curland, if you uninstall this tool and install it again, do you still face this issue? You can do that by following the steps below:

First action, you will need to remove the b4a, you only need to delete the file b4a located at: ```/usr/local/bin/``` .
Open the terminal and run the following commands:
```sudo su```

```curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash```
