### ISSUE TITLE
Install method "GO" not updated and doesn't work as it is currently in README.md

### ISSUE THREAD

**Issue by jaysonng** [back4app/parse-cli#33]
the new line of code should be

`go install github.com/back4app/parse-cli@latest`

instead of what is it is currently 

`go get -t github.com/back4app/parse-cli`

as this produces the error:

```
'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

**Comment by jaysonng** [comment]
and on that note, the [docs](https://www.back4app.com/docs/local-development/parse-cli) don't work for me either as I can't install using 

`curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash`

with errors that says something about python not being found.

**Comment by charles-ramos** [comment]
Thank you, the readme is updated here: https://github.com/back4app/parse-cli/pull/38
