### ISSUE TITLE
Install Back4App CLI

### ISSUE THREAD

**Issue by rafoolin** [back4app/parse-cli#34]
Hello, I followed [Local Development](https://www.back4app.com/docs/local-development/parse-cli) tutorial and in order to install the `Back4App CLI`, ran the following command on my Mac:

```bash
curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash
```

It failed even by using `sudo`. In the end I understood that in the `installer.sh` on [this line](https://github.com/back4app/parse-cli/blob/ec307407b36d4dfd07f722e1ef3a851aafd20069/installer.sh#L11) , you're using `python`, but on my machine`python3` was recognized not `python`.  By replacing `python` by `python3` I was able to install it.

I guess it would be good to cover this in the shell script or add a hint about it similar to `sudo` one.

**Comment by igorfastronicorrea** [comment]
I have same error, fix for this? My mac is an M1

**Comment by rafoolin** [comment]
> I have same error, fix for this? My mac is an M1

I don't know if there is any update or fix for it or not, but what worked for me with my M1 Mac as I said, was changing the bash script.

You can download [this script](https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh) and then change `python` to `python3` or some other similar changes and and then run:

```bash
bash installer.sh
```

**Comment by marcosdourados** [comment]
> I have same error, fix for this?

I have same error, fix for this?

**Comment by pedigru3** [comment]
Same error here

**Comment by pedigru3** [comment]
> > I have same error, fix for this? My mac is an M1
> 
> I don't know if there is any update or fix for it or not, but what worked for me with my M1 Mac as I said, was changing the bash script.
> 
> You can download [this script](https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh) and then change `python` to `python3` or some other similar changes and and then run:
> 
> ```shell
> bash installer.sh
> ```

Thank you very much!

**Comment by richardgroves** [comment]
Same problem still exists many months later. Thanks @pedigru3 for the fixed script.

**Comment by sworteu** [comment]
The script can be adapted to run without python, this uses grep natively:

```
#!/bin/bash

TMP_FILE=/tmp/back4app.tmp
if [ -e ${TMP_FILE} ]; then
  echo "Cleaning up from previous install failure"
  rm -rf ${TMP_FILE}
fi
echo "Fetching latest version ..."

# latest="3.0.6-beta-5"
latest=$(curl https://parsecli.back4app.com/supported?version=latest | grep -oP '(?<="version": ")[^"]*' infile)

case `uname -pm` in
  "x86_64 x86_64" )
      url="https://github.com/back4app/parse-cli/releases/download/release_${latest}/b4a_linux";;
  "x86_64 unknown" )
      url="https://github.com/back4app/parse-cli/releases/download/release_${latest}/b4a_linux";;
  "x86_64 i386" )
      url="https://github.com/back4app/parse-cli/releases/download/release_${latest}/b4a";;
  "aarch64 unknown" )
      url="https://github.com/back4app/parse-cli/releases/download/release_${latest}/b4a_linux";;
  "arm64 arm" ) 
      url="https://github.com/back4app/parse-cli/releases/download/release_${latest}/b4a_mac_m1";;
esac

echo "Version ${latest} will be installed"
curl --progress-bar --compressed -Lo ${TMP_FILE} ${url}

if [ ! -d /usr/local/bin ]; then
  echo "Making /usr/local/bin"
  mkdir -p /usr/local/bin
fi

echo "Installing ..."
mv /tmp/back4app.tmp /usr/local/bin/b4a
chmod 755 /usr/local/bin/b4a

echo "Installation finished"
```

save as b4a-cli-install.sh and don't forget to chmod +x

**Comment by SebaBoler** [comment]
same error.
How run on M1 properly?

**Comment by charles-ramos** [comment]
https://github.com/back4app/parse-cli/pull/37
