### ISSUE TITLE
b4a deploy ignores .well-known directory

### ISSUE THREAD

**Issue by mohitongit** [back4app/parse-cli#35]
We are trying to add _**apple-app-site-association**_ file under _**.well-known**_ directory as described by Apple here: https://developer.apple.com/documentation/xcode/supporting-associated-domains.

This directory exists in the public folder (as shown below) but "b4a deploy" simply ignores it and deploys everything else. I was able to manually create this directory via back4app dashbaord though. Am I missing any command to support such folders?

![Screenshot 2022-11-22 at 2 12 33 AM](https://user-images.githubusercontent.com/4804502/203154841-c3aca68d-3092-4c6f-9ba4-664c9632aa69.jpg)

Thanks,
Mohit

**Comment by mohitongit** [comment]
If this helps: 

I ran b4a deploy with force flag and after normal files are uploaded, this is the end of the output:

![Image 29-11-22 at 12 29 AM (1)](https://user-images.githubusercontent.com/4804502/204608471-5e627b86-baca-4810-b5d5-635087eb99e2.jpg)

This clearly shows b4a deploy is ignoring this folder.

**Comment by charles-ramos** [comment]
Please, try the following workaround 
Upload a folder named "well-known" (without the .), and then, create a custom route. 
For that, create a file named "app.js" in your "cloud" folder, with the following content:
 
```
const path = require('path');
 
app.get('/.well-known/apple-app-site-association', (req, res) => {
   res.sendFile(path.join(`${__dirname}/public/well-known/apple-app-site-association`));
})
```
 
Do not forget to create a subdomain for your app, as described here: https://www.back4app.com/docs/platform/activating-web-hosting, then, you'll be able to access it as an endpoint.
